package com.digitalhealth.service;
import com.digitalhealth.dto.HealthRecordDTO; import com.digitalhealth.model.*; import com.digitalhealth.repository.*; import org.springframework.http.*; import org.springframework.stereotype.Service; import org.springframework.web.server.ResponseStatusException; import java.util.*;
@Service public class HealthRecordService {
 private final HealthRecordRepository records; private final WorkerRepository workers;
 public HealthRecordService(HealthRecordRepository records, WorkerRepository workers){this.records=records;this.workers=workers;}
 public HealthRecordDTO create(Long workerId, HealthRecordDTO d){ HealthRecord r=apply(d,new HealthRecord()); r.setWorker(worker(workerId)); return dto(records.save(r)); }
 public List<HealthRecordDTO> list(Long workerId, RecordType type){worker(workerId); return records.findByWorkerIdAndRecordTypeOrderByRecordDateDesc(workerId,type).stream().map(this::dto).toList();}
 public HealthRecordDTO update(Long workerId,Long id,HealthRecordDTO d){ HealthRecord r=records.findById(id).filter(x->x.getWorker().getId().equals(workerId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Health record not found")); return dto(records.save(apply(d,r))); }
 private Worker worker(Long id){return workers.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Worker not found"));}
 private HealthRecord apply(HealthRecordDTO d, HealthRecord r){r.setRecordType(d.getRecordType());r.setRecordDate(d.getRecordDate());r.setRecordTime(d.getRecordTime());r.setTitle(d.getTitle());r.setProvider(d.getProvider());r.setHealthcareCenter(d.getHealthcareCenter());r.setSymptoms(d.getSymptoms());r.setObservations(d.getObservations());r.setDiagnosis(d.getDiagnosis());r.setTreatmentDetails(d.getTreatmentDetails());r.setNotes(d.getNotes());r.setMedicineName(d.getMedicineName());r.setDosage(d.getDosage());r.setFrequency(d.getFrequency());r.setDuration(d.getDuration());r.setInstructions(d.getInstructions());r.setFollowUpDate(d.getFollowUpDate());r.setStatus(d.getStatus());r.setVaccineName(d.getVaccineName());r.setDoseNumber(d.getDoseNumber());r.setNextDoseDate(d.getNextDoseDate());return r;}
 private HealthRecordDTO dto(HealthRecord r){HealthRecordDTO d=new HealthRecordDTO();d.setId(r.getId());d.setRecordType(r.getRecordType());d.setRecordDate(r.getRecordDate());d.setRecordTime(r.getRecordTime());d.setTitle(r.getTitle());d.setProvider(r.getProvider());d.setHealthcareCenter(r.getHealthcareCenter());d.setSymptoms(r.getSymptoms());d.setObservations(r.getObservations());d.setDiagnosis(r.getDiagnosis());d.setTreatmentDetails(r.getTreatmentDetails());d.setNotes(r.getNotes());d.setMedicineName(r.getMedicineName());d.setDosage(r.getDosage());d.setFrequency(r.getFrequency());d.setDuration(r.getDuration());d.setInstructions(r.getInstructions());d.setFollowUpDate(r.getFollowUpDate());d.setStatus(r.getStatus());d.setVaccineName(r.getVaccineName());d.setDoseNumber(r.getDoseNumber());d.setNextDoseDate(r.getNextDoseDate());return d;}
}
